### ISSUE TITLE
fix damper adjustment range

### ISSUE THREAD

**Issue by macbethmotorsport** [macbethmotorsport/aeh#7]
in the setup menu, the dampers are completely maxed out 

TODO: post screenshot for reference. 

fix / figure out why

**Comment by macbethmotorsport** [comment]
current: 

![fuckeddampers](https://user-images.githubusercontent.com/50679709/57981399-32779b00-7a37-11e9-896f-93d32f5a44ec.png)

**Comment by macbethmotorsport** [comment]
fixed. discrepancy explained below: 

from suspensions.ini
```
DAMP_BUMP=10800									; Damper wheel rate stiffness in N sec/m in slow speed compression
DAMP_FAST_BUMP=9500							; Damper wheel rate stiffness in N sec/m in fast speed compression
DAMP_FAST_BUMPTHRESHOLD=0.0					; Damper bump slow/fast threshold in seconds
DAMP_REBOUND=6800								; Damper wheel rate stiffness in N sec/m in slow speed rebound
DAMP_FAST_REBOUND=6000						; Damper wheel rate stiffness in N sec/m in fast speed rebound
DAMP_FAST_REBOUNDTHRESHOLD=0.0	
```

...then making sure in **setup.ini**, the values above are within the MIN/MAX range, as below: 
```
[DAMP_BUMP_LF]
<cut>
MIN=50
MAX=20000
<cut>
```

Now we have adjustability! :D 
![dampers2](https://user-images.githubusercontent.com/50679709/57981760-70c38900-7a3c-11e9-908a-b5d056cdb778.png)

**Comment by djhedges** [comment]
I suspect the Konis we're about to get will be no where near as nice.
